let productData = [
    {
        name : 'ROADSTAR WATCH',
        catagories: 'watch_roadstar',
        price : 500,
        image: 'image/products/product (1).jpg',
        id : '1',
    },
    {
        name : 'NIKE PANTS',
        catagories: 'men_pants_nike_long_boy',
        price : 20,
        image: 'image/products/product (2).jpg',
        id : '2',
    },
    {
        name : 'PUMA SHIRT',
        catagories: 'men_shirts_puma_boy',
        price : 50,
        image: 'image/products/product (3).jpg',
        id : '3',
    },
    {
        name : 'HRX SHOES',
        catagories: 'hrxshoes_shoes_men_shoes',
        price : 30,
        image: 'image/products/product (4).jpg',
        id : '4',
    },
    {
        name : 'BENETTON PANTS',
        catagories: 'benetton_men_pants_boy',
        price : 50,
        image: 'image/products/product (5).jpg',
        id : '5',
    },
    {
        name : 'PUMA SHIRT',
        catagories: 'men_shirts_puma_boy',
        price : 11,
        image: 'image/products/product (6).jpg',
        id : '6',
    },
    {
        name : 'FOSSIL WATCH',
        catagories: 'watch_fossil',
        price : 300,
        image: 'image/products/product (7).jpg',
        id : '7',
    },
    {
        name : 'NIKE SHOES',
        catagories: 'nike_men_shoes',
        price : 50,
        image: 'image/products/product (8).jpg',
        id : '8',
    },
    {
        name : 'PUMA SHIRT',
        catagories: 'pumashirt_men_shirt_boy',
        price : 50,
        image: 'image/products/product (9).jpg',
        id : '9',
    },
    {
        name : 'APPLE WATCH SE',
        catagories: 'apple_smartwatch_watch',
        price : 500,
        image: 'image/products/product (10).jpg',
        id : '10',
    },
    {
        name : 'I PHONE 12',
        catagories: 'apple_iphone12black_phone',
        price : 959,
        image: 'image/products/product (11).png',
        id : '11',
    },
    {
        name : 'I PAD PRO(2020)',
        catagories: 'apple_ipadpro_tablet',
        price : 1300,
        image: 'image/products/product (12).jpg',
        id : '12',
    },
    {
        name : 'MAC BOOK PRO',
        catagories: 'apple_macbookpro_laptop_pc',
        price : 1449,
        image: 'image/products/product (13).jpg',
        id : '13',
    },
    {
        name : 'SAMSUNG A12',
        catagories: 'samsung_a12_phone',
        price : 239,
        image: 'image/products/product (14).jpg',
        id : '14',
    },
    {
        name : 'GIRL BLACK T-SHIRT',
        catagories: 'Girl_black_Tshirt_tops',
        price : 3,
        image: 'image/products/product (15).jpg',
        id : '15',
    },
    {
        name : 'LANTERN SLEEVES BLOUSE',
        catagories: 'Girl_RENE_Lantern_Sleeves_Blouse_tops',
        price : 30,
        image: 'image/products/product (16).jpg',
        id : '16',
    },
    {
        name : 'PEACEMINIMOUSE T-SHIRT',
        catagories: 'Girl_peaceminimouse_t-shirt_Tshirt_tops',
        price : 8,
        image: 'image/products/product (17).jpg',
        id : '17',
    },
    {
        name : 'PLATED SKIRT',
        catagories: 'Girl_pink_platedskirt',
        price : 10,
        image: 'image/products/product (18).jpg',
        id : '18',
    },
    {
        name : 'H&M T-SHIRT',
        catagories: 'boy_h&m_t-shirt_tshirt_men',
        price : 25,
        image: 'image/products/product (19).jpg',
        id : '19',
    },
    {
        name : 'H&M HEEL',
        catagories: 'girl_heel_h&m',
        price : 40,
        image: 'image/products/product (20).jpg',
        id : '20',
    },
    {
        name : 'OFFSHOLDER BLOUSE',
        catagories: 'Girl_RENE_Blouse_tops_offsholderblouse',
        price : 30,
        image: 'image/products/product (21).jpg',
        id : '21',
    },
    {
        name : 'FLOWER TYPE LACE SKIRT',
        catagories: 'Girl_RENE_Mattias_Flower_type_lace_Skirts',
        price : 36,
        image: 'image/products/product (22).jpg',
        id : '22',
    },
];

let userData = [
    {
        username : 'admin1',
        name : 'Shein Min Htet 1',
        password : '12345678',
        email : 'admin1@gmail.com',
        phone : +959123456789,
        img : "image/common/user (1).png",
    },
    {
        username : 'admin2',
        name : 'Shein Min Htet 2',
        password : '12345678',
        email : 'admin2@yandex.com',
        phone : +959364234567,
        img : "image/common/user (2).png",
    },
    {
        username : 'admin3',
        name : 'Shein Min Htet 3',
        password : '12345678',
        email : 'admin3@gmail.com',
        phone : +959786548764,
        img : "image/common/user (3).png",
    },
]